[workspace]
members = ["launcher", "yuzuha", "yuzuha/yuzuha-codegen"]
resolver = "2"

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
windows = "0.59.0"
ilhook = "2.1.1"
thiserror = "2.0.11"
num_enum = "0.7.3"
